### ISSUE TITLE
コメント

### ISSUE THREAD

**Issue by yuuki00682200** [kojake/featherdash#1]
最近どうでしょうか？今週土曜日久しぶりの授業なので、何か先に見ておいて欲しいものなどあればコメントください〜

**Comment by kojake** [comment]
高津さん
お久しぶりです

学校は楽しくやっていけています。
で、あのドローンの話なんですが許可が降りませんでした。
もう飛行機のチケット取っちゃいましたか?・・・

海斗

**Comment by yuuki00682200** [comment]
飛行機のチケットは取ったけど、ビザが降りるかわかりません、、！
日曜日の飛行機にしたので、土曜日はどのみち大丈夫ですよ〜🙆‍♀️
